version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: shicham
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - django_network

  backend:
    build: ./backend
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://niboukha:1234@db:5432/mydatabase
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - db
      - redis
    networks:
      - django_network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - django_network

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80"
    networks:
      - django_network

  pgadmin:
    image: dpage/pgadmin4:6.3
    environment:
      - PGADMIN_DEFAULT_EMAIL=niboukha@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1234
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - django_network

volumes:
  postgres_data:

networks:
  django_network:
